# Generated by Django 3.2.7 on 2021-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('product_advice', 'Product Advice'), ('technical_support', 'Technical Support'), ('general_feedback', 'General Feedback')], default='general_enquiry', max_length=120)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=90)),
                ('message', models.TextField(max_length=3000)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Page Submissions',
            },
        ),
    ]
