# Generated by Django 3.2.7 on 2022-01-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='enrolled',
        ),
    ]
